In [11]:
print("Hemlo")

Hemlo


In [1]:
import numpy as np
import time

`Note:` If multiple types of data exist arr is converted to string.


In [2]:
arr1=np.array((1,2,3,"Adnan"))

In [3]:
arr1

array(['1', '2', '3', 'Adnan'], dtype='<U21')

In [4]:
np_arr=np.array([[1,2,4],[3,2,1]])

In [5]:
np_arr*4

array([[ 4,  8, 16],
       [12,  8,  4]])

In [6]:
np.transpose(np_arr) 

array([[1, 3],
       [2, 2],
       [4, 1]])

In [7]:
t1 = time.time()
a2 = np.arange(0, 10**9, 5)
t2 = time.time()
print("array Creation time: ", t2 - t1) # 0.716s

array Creation time:  1.3067259788513184


In [8]:
t1=time.time()
l2=[i for i in range(0,10**9,5)]
t2=time.time()

print("List Creation time: ", t2 - t1) 

List Creation time:  41.03713083267212


In [9]:
z1=np.zeros((3,4))
z1

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [10]:
o1=np.ones((1,9))
o1

array([[1., 1., 1., 1., 1., 1., 1., 1., 1.]])